### ISSUE TITLE
Module not found: Error: Can't resolve 'react-twitter-embedded-timeline'

### ISSUE THREAD

**Issue by jackbit** [uraway/react-twitter-embedded-timeline#9]
I got the flowing error when try `import TwitterTimeline from 'react-twitter-embedded-timeline';`

Module not found: Error: Can't resolve 'react-twitter-embedded-timeline'

I have done this command and i checked in package.json it has `"react-twitter-embedded-timeline": "^0.3.3",`
```
$ npm install --save react-twitter-embedded-timeline

+ react-twitter-embedded-timeline@0.3.3
updated 1 package in 6.916s
```

**Comment by uraway** [comment]
Fixed version released. Please upgrade the library.
